version: "3.8"

services:
  app:
    container_name: playground
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 4000:4000
    env_file:
      - .env
